---
# - name: Install nginx
#   yum:
#     name: http://nginx.org/packages/centos/7/x86_64/RPMS/nginx-1.20.2-1.el7.ngx.x86_64.rpm
#     state: present
# - name: Enable nginx
#   service:
#     name: nginx
#     state: started
#     enabled: yes
# - name: Copy config file into conf.d
#   template:
#     src: /home/nma/ansible/roles/nginx/templates/proxy.j2
#     dest: /etc/nginx/conf.d/proxy.conf
#     owner: ec2-user
#     group: ec2-user
#     mode: 0644
- name: Enable nginx repo
  template:
    src: nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  when: nginx_yum_repo_enabled | bool
- name: copy file 2