---
- name: Install epel
  yum: 
    name: epel-release
    state: present
- name: Install nginx
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - nginx

- name: Enable service
  systemd:
    name: '{{item}}'
    state: started
    enabled: yes
  loop:
  - nginx

# - name: Open port 80/443
#   firewalld:
#     zone: public
#     port: 'item'
#     immediate: true
#     permanent: yes
#     state: enabled
  # loop:
  # - 80/tcp
  # - 443/tcp
  # - 22/tcp
  # - 3306/tcp
  # notify: restart firewalld

- name: Copy config file into conf.d
  template:
    src: proxy.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: "{{user}}"
    group: "{{group}}"
    mode: 0644
  notify: restart nginx