---
- name: Download MySQL Community Repo
  get_url:
    url: http://repo.mysql.com/mysql80-community-release-el8.rpm
    dest: /tmp
# - name: Install Mysql Community
#   shell: /bin/rpm -Uvh /tmp/mysql80-community-release-el8.rpm

- name: Install MySQL Server
  yum: 
    name: '{{item}}'
    state: present
  loop:
  - mysql
  - mysql-server
  - firewalld
  - python3

- name: run Service
  service: 
    name: '{{item}}'
    state: started 
    enabled: yes
  loop:
  - mysqld
  - firewalld

- name: Open port 3306
  firewalld:
    zone: public
    port: '{{item}}'
    immediate: true
    permanent: yes
    state: enabled
  loop:
  - 22/tcp
  - 3306/tcp
  notify: restart firewalld

- name: install PyMySQL
  pip: 
    name: pymysql 
    state: present

- name: Change root password
  mysql_user: 
    name: root 
    password: "{{ dbpass }}" 
    priv: "*.*:ALL,GRANT"

- name: copy .my.cnf file with root password credentials
  template: 
    src: my.cnf.j2 
    dest: ~/.my.cnf 
    owner: root 
    mode: 0600
  notify: restart mysql

- name: Remove the test database
  mysql_db: 
    name: test 
    state: absent

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: '' 
    host: '{{ item }}' 
    state: absent
  with_items:
    - 127.0.0.1
    - localhost

