---
- name: Download MySQL Community Repo
  get_url:
    url: http://repo.mysql.com/mysql80-community-release-el8.rpm
    dest: /tmp
- name: Install Mysql Community
  shell: /bin/rpm -Uvh /tmp/mysql80-community-release-el8.rpm

- name: Install MySQL Server
  yum: name={{item}} state=present
  with_items:
  - mysql
  - mysql-server
- name: run Mysql
  service: name=mysqld state=started enabled=yes
- name: Install python3
  dnf: name=python3 state=latest

- name: install PyMySQL
  pip: name=pymysql state=present

- name: Start MySQL Server and enable it
  service: name=mysqld state=started enabled=yes

- name: Remove anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
# - name: Set MySQL root Password
#   mysql_user:
#     login_host: 'localhost'
#     login_user: 'root'
#     login_password: ''
#     name: 'root'
#     password: '12345'
#     state: present
- name: Create user
  mysql_user:
    name: nam
    password: 12345
    host: 10.10.5.147
    priv: '*.*:ALL,GRANT'
    state: present
- name: Cteate database
  mysql_db:
    name: test
    state: present
