---
- name: Set time zone to Asia/Ho_Chi_Minh
  timezone:
    name: Asia/Ho_Chi_Minh

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible
  yum:
    name: ansible
    state: latest

- name: Copy roles playbook dir
  copy:
    src: ~/ansible/roles/
    dest: /home/{{ user }}/roles/
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644

- name: Add ansible.cfg
  template:
    src: ansible.cfg.j2
    dest: /home/{{ user }}/ansible.cfg
    owner: "{{ user }}"
    group: "{{ group }}"  
    mode: 0644

- name: Add hostfile 
  template: 
    src: hosts.j2
    dest: /home/{{ user }}/hosts
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644
- name: Copy playbook user-node
  template:
    src: main.j2
    dest: /home/{{ user }}/user-node-{{item}}.yml
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644
  with_items:
    - nginx
    - mysql
  vars:
    hostnode:
      - nginx
      - mysql
    usernode:
      - nginx
      - mysql
    groupnode:
      - nginx
      - mysql
    keynamenode:
      - nginx
      - mysql

- name: Create ssh key
  openssh_keypair:
    path: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ group }}"  
    mode: 0400
    force: no
  with_items:
    - nginx
    - mysql