---
- name: Set time zone to Asia/Ho_Chi_Minh
  timezone:
    name: Asia/Ho_Chi_Minh

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install ansible
  yum:
    name: ansible
    state: latest

- name: Copy roles playbook dir
  copy:
    src: ~/ansible/roles/
    dest: /home/{{ user }}/roles/
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644
- name: Copy private key
  copy: 
    src: ~/ansible/keys/namtp
    dest: /home/{{ user }}/namtp
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0400
- name: Create file playbook
  template:
    src: playbook.j2
    dest: /home/{{ user }}/{{usernode}}.yml
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644

- name: Create file playbook user-mysql
  template:
    src: usermysql.j2
    dest: /home/{{ user }}/usermysql.yml
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644
  when: usernode == 'mysql'
- name: Add ansible.cfg
  template:
    src: ansible.cfg.j2
    dest: /home/{{ user }}/ansible.cfg
    owner: "{{ user }}"
    group: "{{ group }}"  
    mode: 0644
    force: no

- name: Add hostfile 
  template: 
    src: hosts.j2
    dest: /home/{{ user }}/host
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644

- name: Copy playbook user-node
  template:
    src: main.j2
    dest: /home/{{ user }}/user-node-{{item}}.yml
    owner: "{{ user }}"
    group: "{{ group }}"   
    mode: 0644
  with_items:
    - "{{usernode}}"

- name: Create ssh key
  openssh_keypair:
    path: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ group }}"  
    mode: 0400
    force: no
  with_items:
    - "{{usernode}}"

- name: Run playbook add user and key into node
  shell: ansible-playbook -i "./host" user-node-{{item}}.yml
  with_items:
    - "{{usernode}}"
    
- name: Add ip into hosts file
  lineinfile:
    path: ./hosts
    line: |
      [{{usernode}}]
      {{ip}} ansible_ssh_user={{usernode}} ansible_ssh_private_key_file=/home/{{user}}/{{usernode}}
    create: yes

- name: Remove private key
  file:
    path: /home/{{ user }}/namtp
    state: absent